redxemoji = '\N{CROSS MARK}'
checkmarkemoji = '\N{WHITE HEAVY CHECK MARK}'

alpha_emoji_dict = {
    'A': '\N{REGIONAL INDICATOR SYMBOL LETTER A}',
    'B': '\N{REGIONAL INDICATOR SYMBOL LETTER B}',
    'C': '\N{REGIONAL INDICATOR SYMBOL LETTER C}',
    'D': '\N{REGIONAL INDICATOR SYMBOL LETTER D}',
    'E': '\N{REGIONAL INDICATOR SYMBOL LETTER E}',
    'F': '\N{REGIONAL INDICATOR SYMBOL LETTER F}',
    'G': '\N{REGIONAL INDICATOR SYMBOL LETTER G}',
    'H': '\N{REGIONAL INDICATOR SYMBOL LETTER H}',
    'I': '\N{REGIONAL INDICATOR SYMBOL LETTER I}',
    'J': '\N{REGIONAL INDICATOR SYMBOL LETTER J}',
    'K': '\N{REGIONAL INDICATOR SYMBOL LETTER K}',
    'L': '\N{REGIONAL INDICATOR SYMBOL LETTER L}',
    'M': '\N{REGIONAL INDICATOR SYMBOL LETTER M}',
    'N': '\N{REGIONAL INDICATOR SYMBOL LETTER N}',
    'O': '\N{REGIONAL INDICATOR SYMBOL LETTER O}',
    'P': '\N{REGIONAL INDICATOR SYMBOL LETTER P}',
    'Q': '\N{REGIONAL INDICATOR SYMBOL LETTER Q}',
    'R': '\N{REGIONAL INDICATOR SYMBOL LETTER R}',
    'S': '\N{REGIONAL INDICATOR SYMBOL LETTER S}',
    'T': '\N{REGIONAL INDICATOR SYMBOL LETTER T}',
    'U': '\N{REGIONAL INDICATOR SYMBOL LETTER U}',
    'V': '\N{REGIONAL INDICATOR SYMBOL LETTER V}',
    'W': '\N{REGIONAL INDICATOR SYMBOL LETTER W}',
    'X': '\N{REGIONAL INDICATOR SYMBOL LETTER X}',
    'Y': '\N{REGIONAL INDICATOR SYMBOL LETTER Y}',
    'Z': '\N{REGIONAL INDICATOR SYMBOL LETTER Z}'
}
